name: Sync Release

on:
  push:
    branches: [ master ]

jobs:
  sync-release:
    runs-on: ubuntu-latest
    - name: Make Release PR
      uses: tretuna/sync-branches@1.2.0
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        FROM_BRANCH: ${{ github.ref }}
        TO_BRANCH: "release"