name: Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn
    - name: Type Check
      run: yarn type-check
    - name: Jest Annotations & Coverage
      uses: mattallty/jest-github-action@v1.0.3
      with:
        test-command: yarn test --coverage
    - name: Merge to Release
      uses: everlytic/branch-merge@1.1.0
      with:
        github_token: ${{ github.token }}
        source_ref: ${{ github.ref }}
        target_branch: 'release'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'




